### ISSUE TITLE
Testi-issue

### ISSUE THREAD

**Issue by juhotoivonen** [tyoelamasimulaattori/tyoelamasimulaattori#1]
Tämä on testi-issue

**Comment by rikukissa** [comment]
Pitäisköhän meidän alkaa käyttää näitä issueita nyt esimerkiksi design-päätöksien tekemiseen? Saisi kaikki päätökset yhteen paikkaan selattavaksi. Se Redmine-integraatio on tietenkin pieni ongelma, mutta ei se niin iso vaiva olis tehdä sinne uutta issueta samalla kun lisää tänne.

**Comment by annijanger** [comment]
Hyvä idea kyllä! Flowdockiin kyllä tuppaa hukkua kaikki oleellinen tieto :D

**Comment by rikukissa** [comment]
Joku™ vois tehdä uuden issuen ja liittää sinne kaikki tähän mennessä tulleet design ideat ja materiaalit
