### ISSUE TITLE
Loppunäkymän kuva

### ISSUE THREAD

**Issue by tuulik** [tyoelamasimulaattori/tyoelamasimulaattori#10]
MockCaseNewVersion -tiedostossa on nyt myös loppustepeissä joku kuva. Loppunäkymässä voisi sitten näyttää tuon kuvan pizzan sijasta.

**Comment by MartinHeath** [comment]
Säädin loppuselvennyksen viereisen kuvan vaihtumaan, mutten vielä säätänyt suurempaa kuvaa, sillä siihen ei ole soveltuvaa placeholderia.
