### ISSUE TITLE
S3: Muutoksia sisältöihin

### ISSUE THREAD

**Issue by juhotoivonen** [tyoelamasimulaattori/tyoelamasimulaattori#11]
- Kyvykkyystekijävalinnassa kyvykkyystekijä korvataan sanalla näkökulma
  - Käyttäjälle helpompi ja pelin kannalta kuvaavampi käsite
  - Esim. tervetuloa-näkymässä voidaan kuitenkin valottaa, että _näkökulmat pohjautuvat organisaation kyvykkyystekijöihin..._
- Democasen nimi: Kaija (ja varmaan mätsäävä kuva)
  - Muutenkin casejen nimet ihmisten nimiä
  - Ei haluta paljastaa casevalinnassa casesta mitään muuta kuin vastapuolen nimi/kuva
- Democaseen Matti Meikäläisen tilalle Kaija (ja varmaan mätsäävä kuva)
  - Titteli: Asiantuntijasairaanhoitaja
  - Kaijalla on 13 vuoden kokemus ammatistaan
  - Kaijalla on mies ja kaksi kouluikäistä lasta
  - Vapaa-ajallaan Kaija tykkää käydä tanssimassa salsaa

EDIT: Pieni lisäys:
- Lisämateriaalihaitariin
  - GROW:n tilalle _Valmentava johtaminen_
  - Vihjeisiin tulee linkkejä (asiakas toimittelee)

**Comment by MartinHeath** [comment]
Kaija - case iconi lisätty toimintakulttuurin alle.

**Comment by annijanger** [comment]
Tästä taitaa olla kaikki muu tehtynä paitsi noi lisämateriaalit?

**Comment by juhotoivonen** [comment]
Jäljellä (tai huomioitavaa):
- Muutenkin casejen nimet ihmisten nimiä
- Ei haluta paljastaa casevalinnassa casesta mitään muuta kuin vastapuolen nimi/kuva

_(Tämä siis kun lisätään täytecaseja valintaan)_
- Lisämateriaalihaitariin
  - Vihjeisiin tulee linkkejä (asiakas toimittelee)

_(Tämänhän voisi toteuttaa jo random linkeillä, ovatko sitten pop-upeja?)_

Siirretään nämä seuraaviin sprintteihin.
