### ISSUE TITLE
Projekti katselmointi I satoa (18.3.2015)

### ISSUE THREAD

**Issue by Fairydusti** [tyoelamasimulaattori/tyoelamasimulaattori#13]
- makiaho gittiin
- Stepin jälkeinen palaute/näkymä [valinta->välinäkymä ( mitä valinnasta seuraa) -> uudet valinnat]
- Haitarin materiaalit avautuvat mahdollisesti uuteen ikkunaan
- Loppunäkymä (vastassa olevan "DiSC persoonan" kuvausta. Polun mukaista palautetta)
- Panostusta graafiseen ilmeeseen (etenkin step näkymään)[toim.huom. eka pitä saada varsinaiset steppimateriaalit?]

Käytettävyyteen liittyviä huomioita:
- Koko haitarin palkki avaa materiaalin, ei pelkkä teksti
- "Näkökulman valinta"-näkymään mahdollisesti caseille otsikko,
  sillä erottaako käyttäjä näiden vaihtoehtojen olevan caseja?
- Toiminnallisissa kuvakkeissa/linkeissä/asioissa (kuten casen valintaikoni)  kursori ei muutu tällä hetkellä. (Seuraus, onko kyseessä toiminnallinen objekti?)

**Comment by rikukissa** [comment]
~~makiaho gittiin~~

**Comment by juhotoivonen** [comment]
Täydennän aiemmilla ajatuksilla Sprint 3:n mahdollisesta sisällöstä:
- Casen rakenteen ja flow’n uusiminen, back end ja front end (R9) _(#12)_
- Demon sisältöjen lisääminen _(#11)_
- Design ja kuvitus, näkymät (R1, R4, R5, R11) _(esim. pshp-värit, logon käyttö, steppikuvat...)_
- Tulosnäkymät? (R10) _(valinnan ja seuraavan stepin väliin tulosnäkymä?)_
- Vihjeet (R6) _(mm. toimintajärjestelmäkolmiohässäkkä)_
- Yksikkötestaus _(testien kirjoittaminen)_
- Ensimmäiset käytettävyystestit? _(suunnittelu)_
