### ISSUE TITLE
Caset, stepit, personit kannasta fronttipuolen käyttöön (jsonin sijasta)

### ISSUE THREAD

**Issue by tuulik** [tyoelamasimulaattori/tyoelamasimulaattori#18]
Casen tiedot saa tekemällä getin osoitteeseen: /api/cases/case/{casen id}
Caseen liittyvät stepit samoin getillä: /api/cases/steps/{casen id}
Caseen liittyvän personin tiedot getillä: /api/cases/person/{casen id}
Stepin vastausvaihtoehdot getillä: /api/steps/options/{stepin id}
Kaikki vihjeet getillä: /api/tips/index
Tietty vihje getillä: /api/tips/tip/{vihjeen id}

Nuo kaikki siis palauttaa suoraan json-stringejä.

En ole ihan varma, mihin kohtaan ja miten nuo olisi parasta sinne javascriptiin laittaa. case/index.jsx ja step/index.jsx -tiedostoissa haetaan tällä hetkellä tuo MockCase.json, eli sen voisi jotenkin korvata http-getillä. Samoin siellä, missä haetaan Tips.json, voisi hakea http-getillä vihjeet kannasta.

**Comment by rikukissa** [comment]
Tässä kohtaa voisi varmaan alkaa harkita jo jotain oikeaa arkkitehtuuria fronttipuolelle, ettei varsinaista logiikkaa tarvisi implementoida näkymäkomponentteihin. [RefluxJS](https://github.com/spoike/refluxjs) voisi olla esimerkiksi hyvä vaihtoehto. Sen idea hieman yksinkertaistettuna on, että näkymistä lähtee lähtee kutsuja "actioneihin", jotka voivat esimerkiksi hakea caset tietokannasta ja jotka syöttävät nämä caset "storeille" joiden tarkoitus on säilyttää kaikki applikaation data. Näkymät ja muut komponentit hakevat kaiken datan näiltä storeilta eikä näin itse applikaation tilaa eikä logiikkaa täytyisi säilyttää näkymäkomponenteissa. 

Voin väsäillä vaikka jonkun pienen esimerkin tuosta koodiin. Ajatuksia?

**Comment by tuulik** [comment]
Kuulostaa ihan järkevältä minusta. Kiva, jos voit tehdä tuosta jonkun esimerkin.

**Comment by tuulik** [comment]
Huomasin muuten, että nuo urlit eivät toimi tuolla codeshipin puolella. Localhostilla toimii kyllä hyvin...

**Comment by rikukissa** [comment]
Joo tuossa onkin issue jo siitä https://github.com/tyoelamasimulaattori/tyoelamasimulaattori/issues/16.

Tuli vielä mieleen, että nuo urlit voisi vielä muuttaa tälläiseen perinteiseen [resurssi konventioon](http://www.restapitutorial.com/lessons/restfulresourcenaming.html)
- /api/cases/{casen id}
- /api/cases/{casen id}/person/
- /api/cases/{casen id}/steps/
- /api/cases/{casen id}/steps/{stepin id}
- jne

Datan määrästä riippuen voisi olla ehkä ihan järkevää, että jo `/api/cases/{casen id}` palauttaisi kaiken casen aloittamiseen tarvittavan datan (stepit, steppien sisällä niiden optionit) niin ei tarvisi enää latailla mitään casen ollessa jo käynnissä.
