### ISSUE TITLE
Yhteensopivuusongelmat, IE8 ja IE9

### ISSUE THREAD

**Issue by juhotoivonen** [tyoelamasimulaattori/tyoelamasimulaattori#22]
Lopullista versiota demosta voinee esitellä esimerkiksi Google Chromella, mutta listataan tämä tänne joka tapauksessa. Testailtu IE11:llä IE8- ja IE9-tilassa, sijainnissa http://178.62.158.44/
Nämä pitäisi kyllä testata paikallisestikin.

IE8:ssa ei pääse edes alkunäkymään (_property or method isArray is not supported by the object_)

![ie8](https://cloud.githubusercontent.com/assets/10712222/6769849/87d58a94-d0b3-11e4-9aae-8e7d24373ea6.JPG)

IE9:ssä pääsee alkunäkymään, mutta case-valinta antaa 404:n.

**Comment by rikukissa** [comment]
IE8 voi olla aika työläs saada toimimaan. IE9 voi vielä yrittää, mutta onko tarpeellista demon kannalta?

**Comment by juhotoivonen** [comment]
Kysäistäänpä tämän tarpeellisuudesta katselmoinnissa pe 10.4.

**Comment by juhotoivonen** [comment]
Katselmoinnissa sovittiin, että tähän ei tarvitse käyttää aikaa. Riittää että sovellus toimii Chromella. Lisäksi sovelluksesta tehdään esittelyvideo.
