### ISSUE TITLE
Kirjautuminen

### ISSUE THREAD

**Issue by annijanger** [tyoelamasimulaattori/tyoelamasimulaattori#26]

**Comment by juhotoivonen** [comment]
Elikkäs tähän taisi tulla kokonaisuudessaan...
- Kirjautumispainike (sisään ja ulos)
- Kirjautumistiedot (kun kirjautuneena sisään)
- Linkki case-editoriin (kun kirjautuneena sisään ylläpitäjänä, eli demossa aina kun kirjautuneena sisään)

?

**Comment by rikukissa** [comment]
![login](https://cloud.githubusercontent.com/assets/1206987/7019512/7e17cc66-dd19-11e4-98fd-55b18613cb1f.gif)

Tuo sisäänkirjautumisen jälkeen näkyvä profiilinappi voisi aukaista dropdownin jossa olisi linkki case-editoriin ja uloskirjautuminen vähän samaan tapaan kuin esimerkiksi airbnb:ssä
![dropdown](https://cloud.githubusercontent.com/assets/1206987/7019560/fb8bbe82-dd19-11e4-824f-e952a30984f0.gif)

**Comment by juhotoivonen** [comment]
#31:
- Kirjautumispalkki jo casevalintanäkymään?
- Kirjautuminen esim. tervetuloa-ruutuun
- Uusi peli / Jatka peliä (kirjautuneena, esim. ihan vaan linkki johonkin steppiin)
- Unohditko salasanasi? (kirjoita spostiosoite -> "uusi salasana lähetetty")
  - Onko oleellinen?

**Comment by rikukissa** [comment]
- [x] Kirjautumispalkki jo casevalintanäkymään?
- [x] Kirjautuminen esim. tervetuloa-ruutuun

**Comment by MartinHeath** [comment]
Voisin yrittää kattella tota uusi peli/ jatka settiä

**Comment by MartinHeath** [comment]
- [x] Uusi peli / Jatka peliä (kirjautuneena, esim. ihan vaan linkki johonkin steppiin)

**Comment by annijanger** [comment]
Aiotaanko tuota "Unohditko salasanasi (kirjoita spostiosoite -> "uusi salasana lähetetty")" -ominaisuutta toteuttaa? Onko se siis edelleen vaatimuksena? Onko siitä keskusteltu Jounin kanssa?
