### ISSUE TITLE
Ohjeiden näkyminen pelissä

### ISSUE THREAD

**Issue by Fairydusti** [tyoelamasimulaattori/tyoelamasimulaattori#28]
Käyttäjällä tulee olla pelin ohjeet näkyvissä kaikissa näkymissä pelin aikana!
Tällä hetkellä:
Käyttäjä: Lopeta peli -> kun tarvitset ohjeita. (Näkyvissä ainoastaan aloitussivulla.)

Mahdollisia toteutuksia:
- kysymysmerkki-pallero
- "Ohje"-linkki

Minne?
- tulevaan yläpalkkiin?
- sivupalkkiin?
- muualle?

**Comment by annijanger** [comment]
Ohjeet löytyy nyt alotusnäkymästä ja steppinäkymästä. Tarvitaanko omaansa enää loppunäkymään, vai onko tää issue käsitelty?

**Comment by annijanger** [comment]
... toisaalta siinä näkökulmanäkymässä kun painaa sitä ?-nappulaa tulee se tervetuloanäkymä esiin, missä on pakko kirjautua että pääsee eteenpäin. Tätä pitää varmaan muokata?
