### ISSUE TITLE
S4: Muutoksia sisältöön

### ISSUE THREAD

**Issue by juhotoivonen** [tyoelamasimulaattori/tyoelamasimulaattori#29]
Sprint 3:sta (#11) jääneitä:
- Muutenkin casejen nimet ihmisten nimiä
- Ei haluta paljastaa casevalinnassa casesta mitään muuta kuin vastapuolen nimi/kuva

_(Tämä siis kun lisätään täytecaseja valintaan)_
- Lisämateriaalihaitariin
  - Vihjeisiin tulee linkkejä (asiakas toimittelee)

_(Tämänhän voisi toteuttaa jo random linkeillä, ovatko sitten pop-upeja?)_

**Comment by rikukissa** [comment]
- [x] Muutenkin casejen nimet ihmisten nimiä
- [x] Ei haluta paljastaa casevalinnassa casesta mitään muuta kuin vastapuolen nimi/kuva

Eli vielä lisämateriaaleihin linkit asiakkaalta ja saadaan tämä suljettua?

**Comment by juhotoivonen** [comment]
Jeps, asiakas toimittaa linkit S4:ää myöhemmissä sprinteissä. Suljetaan tämä pois.
