### ISSUE TITLE
S5: Ajatuksia 14.4.2015

### ISSUE THREAD

**Issue by juhotoivonen** [tyoelamasimulaattori/tyoelamasimulaattori#31]
Lisämateriaalit:
- Näkökulmaotsakkeen (ja selityksen) alle linkki kyvykkyystekijämateriaaliin ja case-kohtaisesti toimintakulttuurimateriaaliin (pop-up)
- Toimintajärjestelmä omaksi otsakkeekseen haitariin. Sisällöksi lyhyt kuvaus toimintajärjestelmästä (mitä ko. asia tarkoittaa), toimintajärjestelmäkuvio ja kuvioon liittyen sepitys pikkukolmioista

Kirjautuminen:
- Kirjautumispalkki jo casevalintanäkymään?
- Kirjautuminen esim. tervetuloa-ruutuun
- Uusi peli / Jatka peliä (kirjautuneena, esim. ihan vaan linkki johonkin steppiin)
- Unohditko salasanasi? (kirjoita spostiosoite -> "uusi salasana lähetetty")
  - Onko oleellinen?

Editori:
- Uusien casejen lisäämiseen pelkästään (ei casejen muokkaamiseen tai lisämateriaalien syöttämiseen)
- "Vain ylläpitäjälle", eli varmaankin ylläpitäjä Matti Mattinen pääsee tuohon kirjauduttuaan sisään... (pop-up?)

Case-näkymä:
- Henkilökorttiajatus, voidaanko toteuttaa?

Sisältö:
- Korjaus alkutilanteen kuvaukseen: "vaikka se on vastoin firman sääntöjä" -> "vaikka se on vastoin sovittuja sääntöjä"

**Comment by annijanger** [comment]
"Näkökulmaotsakkeen (ja selityksen) alle linkki kyvykkyystekijämateriaaliin ja case-kohtaisesti toimintakulttuurimateriaaliin (pop-up)" 
Onkos tätä materiaalia jo jossain? Ja tarkoittaaks tää siis että siihen VALITSE NÄKÖKULMA -kohtaan tulee joku linkki?
