### ISSUE TITLE
.NET Framework 2.0 sdk ei lataudu

### ISSUE THREAD

**Issue by MartinHeath** [tyoelamasimulaattori/tyoelamasimulaattori#4]
Ongelmia npm:n kanssa, kuten muilla pajassa. Olen asentanut .NETin, muttei futaa. Kokeilen jokuväli leikkiä pathin kanssa/boottailla. Katotaan auttaako.

**Comment by rikukissa** [comment]
Minkäslaista erroria se heittää?

**Comment by MartinHeath** [comment]
Se ei pysty käynnistämään .NETiä... asensin sen kyllä, mutta voi olla, että winukka taas vaatii bootia ennen kuin suostuu yhteistyöhön
