### ISSUE TITLE
Case (frontissa) ja loppunäkymä

### ISSUE THREAD

**Issue by tuulik** [tyoelamasimulaattori/tyoelamasimulaattori#5]
Case\index.jsx tarvitsee seuraavaa: 

if(!currentStep.hasOwnProperty(options)) tms. {
  ollaan loppunäkymässä ja tehdään jotain asiaankuuluvaa
}

**Comment by rikukissa** [comment]
Pitäisköhän tehä sillee, että meillä olis 2 erillistä komponenttia; CaseView (nykyinen Case/index.jsx) ja sitte joku CaseEndView joka olis se loppunäkymä. Sitten se komponentti joka aukeaa kun tullaan `case/:caseId/step/:stepId` osoitteella (eli se johon toi route mäpätään [main.js](https://github.com/tyoelamasimulaattori/tyoelamasimulaattori/blob/master/resources/js/main.js) tiedostossa) 
1. Hakis nykyisen casen ja stepin (niinkun nyt case/index.jsx)
2. Päättelis siitä tarviiko näyttää loppunäkymä vai casenäkymä
3. Ehkä myös säilyttäis sen infon niistä käydyistä stepeistä https://github.com/tyoelamasimulaattori/tyoelamasimulaattori/issues/6

**Comment by rikukissa** [comment]
Steppien skeemaan vois varmaan lisätä jonkun `end: Boolean` propertyn joka ilmottais onko se loppunäkymä. Muuten vois oikeastaan jättää noi loppunäkymä-stepit kokonaan pois tietokannasta ja päätellä vaan jostain muusta että viimeisin steppi oli viimeinen, mutta sitte jos halutaan jotai custom tekstejä niihin nii täytyy kuitenki olla jotain kannassa

**Comment by tuulik** [comment]
Joo kyllä niihin tarvii varmaan joku loppupalaute-teksti kumminkin lisätä, eli tarvii olla kannassa kumminkin. Tai selviää varmaan jossain vaiheessa että mitä niihin loppunäkymiin sitten halutaan. :)
