### ISSUE TITLE
Eväste tai joku muu systeemi steppipolun tallentamiseksi

### ISSUE THREAD

**Issue by tuulik** [tyoelamasimulaattori/tyoelamasimulaattori#6]
Varmaan case\index.jsx olisi oikea paikka tälle? Sen jälkeen kun ollaan haettu nykyinen steppi:
 var currentStep = findWhere(steps, {id: parseInt(id)});

Tallennettaisiin evästeenä tai jollain muulla tavalla nykyinen steppi ja loppunäkymässä niitä voisi sitten käyttää kaavion piirtämiseen tms.

**Comment by rikukissa** [comment]
Joo tuo on minunkin mielestä hyvä paikka. Nyt ainakin alustavasti tuon voisi tallentaa ihan vaan vaikka tuon komponentin stateen.  Eli käytännössä tuolla case/index.jsx komponentilla voisi olla metodi [getInitialState](http://facebook.github.io/react/docs/component-specs.html#getinitialstate) tyyliin

``` javascript
getInitialState() {
  return {
    previousSteps: []
  }
}
```

ja aina kun mennään uuteen steppiin niin [setState](http://facebook.github.io/react/docs/component-api.html#setstate):lla laitettaisin tuohon tilaan se edellinen steppi

``` javascript
this.setState({
  previousSteps: this.state.previousSteps.concat(previousStep)
})
```

ja sitten loppunäkymässä luettaisiin tuo tieto tuolta statesta

**Comment by tuulik** [comment]
Joo, kuulostaa järkevämmältä kuin tuo evästesysteemi.

**Comment by rikukissa** [comment]
Katselmoinnissa oli puhetta taas siitä, että tehtävä pitäisi pystyä jättämään kesken ja jatkamaan myöhemmin. Mitäs mietteitä tulee tämän toteuttamisesta?

**Comment by rikukissa** [comment]
Tällehän ei nyt ole tarvetta jos meillä on vaan yksi polku
