### ISSUE TITLE
Casejen ja steppien ID:t alkamaan nollasta

### ISSUE THREAD

**Issue by rikukissa** [tyoelamasimulaattori/tyoelamasimulaattori#7]
Voi aiheuttaa tulevaisuudessa harmia kun JavaScriptissä ja PHP:ssa listojen indeksit alkaa nollasta

https://github.com/tyoelamasimulaattori/tyoelamasimulaattori/blob/master/storage/app/MockCaseNewVersion.json

https://github.com/tyoelamasimulaattori/tyoelamasimulaattori/commit/d0ff8194a96d28d96805e0dadea5f7c50563b05e

**Comment by tuulik** [comment]
Askartelin nuo paikalleen :)

**Comment by rikukissa** [comment]
https://github.com/tyoelamasimulaattori/tyoelamasimulaattori/blob/master/resources/components/case-selector/index.jsx#L60 

Käyttöliittymän linkit voisi muuttaa vielä vastaamaan tätä muutosta

**Comment by MartinHeath** [comment]
Hoidettu.
