### ISSUE TITLE
Vihjeet: Toimintajärjestelmä ja case-kohtaiset strategiset lähtökohdat

### ISSUE THREAD

**Issue by juhotoivonen** [tyoelamasimulaattori/tyoelamasimulaattori#8]
Osana vaatimusta _R6 / Käyttäjänä voin selata vihjeitä ja lisämateriaalia casen kaikissa vaiheissa_

![toimintajarjestelma3](https://cloud.githubusercontent.com/assets/10712222/6673774/530cc190-cc1e-11e4-93b1-5538c36e5721.png)
Sovelluksessa tulisi esittää toimintajärjestelmä(kuva) ja casen strategisten lähtökohtien sijoittuminen toimintajärjestelmään.
- Kuvan tumma toimintajärjestelmäpohja teksteineen
- Strategiset lähtökohdat tekstinä (tässä casessa _arkijohtaminen_, _kulttuuri / motivaatio_)
- hoverilla/onclickillä/tms. ilmestyy tekstiä vastaava värillinen kolmio toimintajärjestelmäpohjan päälle:

![toimintajarjestelma4](https://cloud.githubusercontent.com/assets/10712222/6675721/41f89e9e-cc2b-11e4-8b2b-b266f22ca401.png)

Toimintajärjestelmään liittyy myös 10 kohdan lista strategisista hyvinvointitekijöistä
--> Sijoitetaan kaikki toimintajärjestelmään liittyvä omaksi palasekseen lisämateriaalihaitariin?

**Comment by rikukissa** [comment]
http://codepen.io/rikukissa/pen/GgwMjx

Jos tuossa on tarkoitus hoveraa kaikkia kolmen asian yhteyksistä muodostuvia kolmioita nii, se ei oo kyllä ees mahdollista. Jos kuvitellaan että yks yhteys olis **välineet -> säännöt -> yhteisö** eli vasen puolisko tosta kolmiosta ja jos se on alimmaisena niin sen päällä on **säännöt -> yhteisö -> tekijä** ja **tekijä -> yhteisö -> välineet** jolloin se on kokonaan noiden alla eikä sitä oo mahdollista hoverata

![](http://cdn.meme.am/images/300x/8557459.jpg)

**Comment by annijanger** [comment]
Tästäkö puuttuu enää sisällöt, ja sitten on case closed?
