### ISSUE TITLE
NPM test error :'NODE_PATH' 

### ISSUE THREAD

**Issue by MartinHeath** [tyoelamasimulaattori/tyoelamasimulaattori#9]
Eli NPM test tuottaa seuraavan errorin: 

'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.

Ajettu Git Shellissä ja normi komentorivissä. Sama lopputulos.

**Comment by MartinHeath** [comment]
FIX: 

Muuta package.json tiedoston scripts osuuden kohta "test" seuraavanlaiseksi:

```
"test": "set NODE_PATH=resources&& mocha --compilers js:babel/register resources/components/**/__tests__/*.js"
```

**Comment by rikukissa** [comment]
Tähän pitää keksiä vielä ympäristöstä riippumaton ratkaisu

**Comment by rikukissa** [comment]
``` bash
:: 2>/dev/null || echo "
::::::::::::::::::::::::::: Windows
@ECHO OFF
set NODE_PATH=resources&& mocha --compilers js:babel/register resources/components/**/__tests__/*.js
exit /b %ERRORLEVEL%

" >/dev/null
########################### Unix
#!/bin/bash
export NODE_PATH=resources && node_modules/.bin/mocha --compilers js:babel/register resources/components/**/__tests__/*.js
```

Joku säätää tohon windows komennon kuntoon. Lähinnä tuo mochan polku pitäis saada ohjaamaan node_modules/.bin/mocha binääriin

**Comment by MartinHeath** [comment]
toi pathi näyttää aikalailla samalta ku mikä mulla on package.jasonis

**Comment by rikukissa** [comment]
mutta nyt kun tossa tekee skriptin vaikka testata test.bat ja koittaa ajaa komentorivillä niin se polku ei osoita oikeaan paikkaan ellei sulla ole tuo "mocha" komento pathissa

**Comment by MartinHeath** [comment]
Mulla toimi kun vaan pisti näin:

:: 2>/dev/null || echo "
::::::::::::::::::::::::::: Windows
@ECHO OFF
set NODE_PATH=resources&& node_modules.bin\mocha --compilers js:babel/register resources/components/*_/**tests**/_.js
exit /b %ERRORLEVEL%

" >/dev/null
########################### Unix
#!/bin/bash
export NODE_PATH=resources && node_modules/.bin/mocha --compilers js:babel/register resources/components/*_/**tests**/_.js

**Comment by MartinHeath** [comment]
Toimiikohan tää sit kaikilla?

``` javascript
:: 2>/dev/null || echo "
::::::::::::::::::::::::::: Windows
@ECHO OFF
set NODE_PATH=resources&& node_modules\.bin\mocha --compilers js:babel/register resources/components/**/__tests__/*.js
exit /b %ERRORLEVEL%

" >/dev/null
########################### Unix
#!/bin/bash
export NODE_PATH=resources && node_modules/.bin/mocha --compilers js:babel/register resources/components/**/__tests__/*.js

```
